FROM truefoundrycloud/jupyter:0.2.8-sudo
ENV TORCH_CUDA_ARCH_LIST="7.0 7.5 8.0 8.6 9.0+PTX"
ENV DEBIAN_FRONTEND=noninteractive
USER root
# Install CUDA 11.8
RUN sudo add-apt-repository ppa:flexiondotorg/nvtop -y && \
    apt update && \
    apt install -y --no-install-recommends git curl wget htop nvtop && \
    wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.1-1_all.deb -O /tmp/cuda-keyring_1.1-1_all.deb && \
    dpkg -i /tmp/cuda-keyring_1.1-1_all.deb && \
    apt update && \
    apt install -y --no-install-recommends cuda-toolkit-11-8
USER jovyan
COPY requirements.txt notebook-requirements.txt post-pytorch-requirements.txt /tmp_home/jovyan/llm-finetune/
RUN pip install -U pip wheel setuptools && \
    pip install --no-cache-dir -U -r /tmp_home/jovyan/llm-finetune/notebook-requirements.txt && \
    pip install --no-cache-dir --no-build-isolation -U -r /tmp_home/jovyan/llm-finetune/post-pytorch-requirements.txt
ENV JUPYTER_APP_LAUNCHER_PATH=/home/jovyan/llm-finetune/.jp_app_launcher/
COPY --chown=jovyan:users . /tmp_home/jovyan/llm-finetune/
