name: Build the LLM Finetuning Docker image

on:
  push:
    tags:
      - v*

permissions:
  id-token: write
  contents: read

concurrency:
  group: build-llm-finetune-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_SHA: ${{ github.sha }}
  TAG_PREFIX: "v"

jobs:
  build_image:
    name: Build
    uses: truefoundry/github-workflows-public/.github/workflows/build.yml@v0.1.2
    with:
      image_tag: "v${{ github.sha }}"
      image_artifact_name: llm-finetune
      artifactory_registry_url: ${{ vars.TRUEFOUNDRY_ARTIFACTORY_REGISTRY_URL }}
      artifactory_repository_url: ${{ vars.TRUEFOUNDRY_ARTIFACTORY_PUBLIC_REPOSITORY }}
    secrets:
      artifactory_username: ${{ secrets.TRUEFOUNDRY_ARTIFACTORY_PUBLIC_USERNAME }}
      artifactory_password: ${{ secrets.TRUEFOUNDRY_ARTIFACTORY_PUBLIC_PASSWORD }}

  build_notebook_image:
    name: Build
    uses: truefoundry/github-workflows-public/.github/workflows/build.yml@v0.1.2
    with:
      image_tag: "v${{ github.sha }}"
      image_artifact_name: llm-finetune-notebook
      artifactory_registry_url: ${{ vars.TRUEFOUNDRY_ARTIFACTORY_REGISTRY_URL }}
      artifactory_repository_url: ${{ vars.TRUEFOUNDRY_ARTIFACTORY_PUBLIC_REPOSITORY }}
      dockerfile_path: Dockerfile-notebook
    secrets:
      artifactory_username: ${{ secrets.TRUEFOUNDRY_ARTIFACTORY_PUBLIC_USERNAME }}
      artifactory_password: ${{ secrets.TRUEFOUNDRY_ARTIFACTORY_PUBLIC_PASSWORD }}